version: '3.8'
services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: danilloism
      POSTGRES_PASSWORD: senhatemp123
      POSTGRES_DB: lab
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"