# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build/Deploy - Azure

on:
  push:
    branches:
      - master

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 7.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: npx prisma generate
      - run: pnpm prebuild
      - run: pnpm build
      - run: pnpm test:v
  build:
    runs-on: ubuntu-latest
    needs: tests
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 7.0.0
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: pnpm
      - run: rm nest-cli.json
      - run: mv nest-cli.development.json nest-cli.json
      - run: pnpm install --frozen-lockfile
      - run: npx prisma generate
      - run: pnpm prebuild
      - run: pnpm build

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Delete zipped artifact
        run: rm release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'labferreira'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2BAF3786EAF9490BB9F3827F38F58B8A }}
          package: .
