# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - labferreira

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: apply db migration and build
        run: |
          yarn install --frozen-lockfile
          npx prisma migrate deploy
          yarn run build

      - name: zip build folder
        run: zip dist.zip ./dist -r

      - name: Upload artifact for build job
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.zip
  prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # - name: download build zipped folder
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: dist

      # -

      - run: rm -rf node_modules
      - name: install prod dependencies
        run: yarn install --frozen-lockfile --prod

      - name: zip node_modules folder
        run: zip modules.zip ./node_modules ./package.json yarn.lock -r

      - name: Upload zip file for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: modules
          path: modules.zip
  deploy:
    runs-on: ubuntu-latest
    needs: prod
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download dist artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Download node_modules artifact from prod job
        uses: actions/download-artifact@v3
        with:
          name: modules

      - name: Unzip artifacts
        run: |
          unzip modules.zip
          unzip dist.zip
          rm modules.zip
          rm dist.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'labferreira'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_99A56A0877F540449EB72B31A1B22E2E }}
          package: .
