name: Run tests & check build for prod

on:
  push:
    branches:
      - master

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 7.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm prebuild
      - run: pnpm build
      - run: pnpm test:v
  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 7.0.0
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm prebuild
      - run: pnpm build
